name: Calanity
main: dev.sergeantfuzzy.calanity.CalanityCore
version: 1.0.0
api-version: "1.21"
authors: [ "SergeantFuzzy" ]
description: "Calanity — MMORPG clans/classes/abilities"
website: "https://github.com/SergeantFuzzy/Calanity"

softdepend: [PlaceholderAPI, WorldGuard, Vault]

commands:
  calanity:
    description: Calanity admin & profile
    usage: /<command> <debug|reload|profile>
    aliases: [cala]

  clan:
    description: Clan root command (GUI)
    usage: /<command>

  class:
    description: Class root command (GUI)
    usage: /<command>

  ability:
    description: Ability helpers
    usage: /<command>
